# Project information
site_name: Tom's Development Notes
site_description: A guide to software devlopment and notes.
site_author: Tom Moore

theme:
  name: material
  icon:
    logo: material/book-open-variant
  favicon: assets/favicon.ico
  language: en
  palette:
    scheme: default
    primary: black
    accent: black
  font:
    text: Lato
    code: Roboto Mono
  # font: false
  # remove to be GDPR conform
  #    font:
  #        text: Roboto
  #        code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

  extra_css:
   - assets/extra.css

# Page tree
nav:
  - Home: index.md
  - Bare Metal:
    - Placeholder: bare-metal/placeholder.md
  - Environment:
    - Placeholder: enviroment/placeholder.md
  - Embedded Linux:
    - Linux Operating System :
      - GPIO : embedded/gpio/gpio.md
      - Hwmon : embedded/hwmon/hwmon.md
      - I2C : embedded/i2c/i2c.md
      - IIO : embedded/iio/iio.md
      - LEDs : embedded/leds/leds.md
      - Misc: embedded/misc/misc.md
      - PWM: embedded/pwm/pwm.md
      - Regmap: embedded/regmap/regmap.md
      - Regulator : embedded/regulator/regulator.md
      - RTC : embedded/rtc/rtc.md
      - Serdev : embedded/serdev/serdev.md
      - SPI : embedded/spi/spi.md
      - USB : embedded/usb/usb.md
      - Watchdog : embedded/watchdog/watchdog.md
  - Languages:
    - Placeholder: languages/placeholder.md

